version: "3.5"

services:
  pg_oauth:
    image: postgres:latest
    container_name: pg_oauth
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_OAUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_OAUTH}
      - POSTGRES_HOST=${POSTGRES_HOST_OAUTH}
      - POSTGRES_PORT=${POSTGRES_PORT_OAUTH}
      - POSTGRES_DB=${POSTGRES_DB_OAUTH}
    expose:
      - 5432
  
  fastapi_oauth:
    container_name: fastapi_oauth
    build:
      context: .
      dockerfile: ./oauth/docker/oauth.Dockerfile
    command: >
      sh -c "cd ./src && uvicorn oauth.app:app --host=0.0.0.0 --port=8800"
    depends_on:
      - pg_oauth
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_OAUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_OAUTH}
      - POSTGRES_HOST_OAUTH_FASTAPI=${POSTGRES_HOST_OAUTH_FASTAPI}
      - POSTGRES_PORT=${POSTGRES_PORT_OAUTH}
      - POSTGRES_DB=${POSTGRES_DB_OAUTH}
      - GITHUB_CLINET_ID=${GITHUB_CLINET_ID}
      - GITHUB_CLINET_SECRET=${GITHUB_CLINET_SECRET}
    expose:
      - 8800

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.nginx/nginx.Dockerfile
    restart: always
    depends_on:
      - fastapi_oauth
    ports:
      - "80:80"

    